### ISSUE TITLE
bezit

### ISSUE THREAD

**Issue by druud** [phma/bezitopo#11]
From a Dutch language POV, bezitopo, reads a bit like bezit-topo, and bezit means property, wealth, ownage, occupation, possession :)

**Comment by phma** [comment]
What's wrong with that? One can make a topographical survey of one's property. "Bezi" refers to Bézier surfaces.

I am also aware that some Romance languages call a certain small mammal "topo", which has diverse meanings in other languages.

**Comment by druud** [comment]
Nothing wrong with that! Just anecdotal, and possibly fun to be aware of.

https://www.wordsense.eu/besit/
(the -sess in possess is similar to -zit)
